/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carmen
 */
public class Busqueda extends javax.swing.JFrame {

    private ResultSet resultado;
    private Statement sql;
    DefaultTableModel model;
    String [] datoSelect = new String [4];
    private ArrayList<String> arr = new ArrayList<>();
    private String textoo;

    public String getTextoo() {
        return textoo;
    }

    public void setTextoo(String textoo) {
        this.textoo = textoo;
    }

   

    public ArrayList<String> getArr() {
        return arr;
    }

    public void setArr(ArrayList<String> arr) {
        this.arr = arr;
    }
    /**
     * Creates new form Busqueda
     */
    public Busqueda(String texto) {
        initComponents();
        this.setTextoo(texto);
    }

    public void buscarProducto(String texto) throws IOException {
        try {
            String[] titulos = {"Nombre", "Categoria", "Marca", "Existencia"};
            String filtro = "" + texto + "%";
            String SQLL = "SELECT Productos.id_prd,Productos.prd_nomb, Categorias.cat_nomb,Marcas.mrc_nomb, Productos.prd_exist FROM Productos  JOIN Categorias ON Productos.id_cat=Categorias.id_cat LEFT JOIN Marcas ON Productos.id_mrc=Marcas.id_mrc WHERE prd_nomb like '"+filtro+"' AND Productos.activo='true'  ORDER BY Productos.prd_nomb ASC";
            //String SQL = "select * from productos where prd_nomb like " + "'" + filtro + "' and activo='true'";
            //System.out.println(SQL);
            model = new DefaultTableModel(null, titulos);
            sql = Conexion.conexionbd().createStatement();
            resultado = sql.executeQuery(SQLL);
            String [] fila = new String[6]; 
            while(resultado.next()){
                fila[0]=resultado.getString("prd_nomb");
                fila[1]=resultado.getString("cat_nomb");
                fila[2]=resultado.getString("mrc_nomb");
                fila[3]=resultado.getString("prd_exist");
                model.addRow(fila);
            }
            
            tablaBusProduc.setModel(model);
            resultado.close();
            sql.close();
        } catch (SQLException ex) {
            System.out.println(""+ex.getMessage());
            Logger.getLogger(Busqueda.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    public ArrayList<String> Datos (String texto[])  {
        
        ArrayList<String> arreglo = new ArrayList<String>();
        

            for (int i = 0; i < texto.length; i++) {
                arreglo.add(texto[i]);
            }
        JOptionPane.showMessageDialog(this, "Cambios guardados con éxito en Datos"+arreglo);
        return arreglo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tituloLabel = new javax.swing.JLabel();
        etqNombreBusqueda = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaBusProduc = new javax.swing.JTable();
        campoBusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Busqueda de Productos");
        setBackground(new java.awt.Color(1, 47, 87));
        setBounds(new java.awt.Rectangle(300, 20, 750, 600));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(1, 47, 87));

        tituloLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 40)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("Busqueda de Productos");

        etqNombreBusqueda.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqNombreBusqueda.setForeground(new java.awt.Color(255, 255, 255));
        etqNombreBusqueda.setText("Nombre:");

        tablaBusProduc.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 13)); // NOI18N
        tablaBusProduc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaBusProduc.setRowHeight(20);
        tablaBusProduc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaBusProducMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaBusProduc);

        campoBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoBusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(etqNombreBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tituloLabel))
                .addGap(134, 134, 134))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloLabel)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etqNombreBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(campoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoBusquedaKeyReleased
        try {
            // TODO add your handling code here:
            String buscar=campoBusqueda.getText();
            buscarProducto(buscar);
        } catch (IOException ex) {
            Logger.getLogger(Busqueda.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_campoBusquedaKeyReleased

    private void tablaBusProducMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaBusProducMouseClicked
        // TODO add your handling code here:
        int rec = this.tablaBusProduc.getSelectedRow();
        
        for(int i = 0;i<datoSelect.length;i++){
            datoSelect[i]=tablaBusProduc.getValueAt(rec,i).toString();
            System.out.println("datoSelect----------"+datoSelect[i]);
        }
        this.setArr(Datos(datoSelect));
        
        //System.out.println(this.getArr());
        JOptionPane.showMessageDialog(this, "Cambios guardados con éxito en DatoSelect.... arr="+arr);
        
        
    }//GEN-LAST:event_tablaBusProducMouseClicked

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
    /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(() -> {
            new Busqueda().setVisible(true);
        });
    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoBusqueda;
    private javax.swing.JLabel etqNombreBusqueda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaBusProduc;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
