/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Gamaliel Bernal
 */
public class Devoluciones extends javax.swing.JPanel implements Runnable {

    private Reloj reloj;
    Connection conn = null;
    DevolucionesBD dev = new DevolucionesBD();
    int id, nV, articulos;
    String fecha;

    public Devoluciones(String nombre) throws IOException {
        initComponents();
        reloj = new Reloj();

        this.setSize(100, 100);
        Thread t = new Thread(this);
        t.start();
        fecha();
        getConn();

        botonDevolver.setEnabled(false);
        try {
            dev.consultaVentasGen(tablaContenido);
        } catch (SQLException ex) {

        }
        userName.setText(nombre);
    }

    public Connection getConn() {
        try {
            Class.forName("org.postgresql.Driver");
            conn = DriverManager.getConnection("jdbc:postgresql://127.0.0.1:8088/maja", "postgres", "123456");
            System.out.println(conn.isValid(3000) ? "Conexion correcta" : "Conexion fallida");

        } catch (ClassNotFoundException | SQLException e) {
            System.out.println("Error " + e.getMessage());
        }
        return conn;
    }

    public void fecha() {
        Calendar date = Calendar.getInstance();
        SimpleDateFormat dateformatter = new SimpleDateFormat("E dd/MM/yyyy");
        fechaDevolucion.setText(dateformatter.format(date.getTime()));
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        busqueda = new javax.swing.JTextField();
        lupa = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();
        botonDevolver = new javax.swing.JButton();
        etqFolio = new javax.swing.JLabel();
        folio = new javax.swing.JLabel();
        etqCalendar = new javax.swing.JLabel();
        fechaDevolucion = new javax.swing.JLabel();
        hora = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(1, 47, 83));

        titulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Devoluciones");

        busqueda.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        busqueda.setText("Folio de la venta...");
        busqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                busquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                busquedaFocusLost(evt);
            }
        });
        busqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                busquedaMouseClicked(evt);
            }
        });
        busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                busquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                busquedaKeyTyped(evt);
            }
        });

        lupa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario2.png"))); // NOI18N

        userName.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        userName.setForeground(new java.awt.Color(255, 255, 255));
        userName.setText("Nombre_usuario");

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Cantidad", "Nombre", "Precio", "Presentación"
            }
        ));
        tablaContenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaContenidoMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaContenido);

        botonDevolver.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        botonDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/devoluciones.png"))); // NOI18N
        botonDevolver.setText("Devolver producto");
        botonDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverActionPerformed(evt);
            }
        });

        etqFolio.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        etqFolio.setForeground(new java.awt.Color(255, 255, 255));
        etqFolio.setText("Folio:");

        folio.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        folio.setForeground(new java.awt.Color(255, 255, 255));
        folio.setText("000000");

        etqCalendar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calendario.png"))); // NOI18N

        fechaDevolucion.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        fechaDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        fechaDevolucion.setText("dd-mm-aaaa");

        hora.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        hora.setForeground(new java.awt.Color(255, 255, 255));
        hora.setText("00:00:00");

        jButton1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/devoluciones.png"))); // NOI18N
        jButton1.setText("Devolver venta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botonDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lupa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(titulo)
                                .addGap(128, 128, 128))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(etqCalendar)
                                    .addComponent(user))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(392, 392, 392)
                                        .addComponent(etqFolio)
                                        .addGap(18, 18, 18)
                                        .addComponent(folio))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fechaDevolucion)
                                        .addGap(27, 27, 27)
                                        .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(0, 241, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(titulo)
                        .addGap(164, 164, 164))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lupa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(etqFolio)
                                    .addComponent(folio)
                                    .addComponent(userName))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(etqCalendar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fechaDevolucion)
                                    .addComponent(hora, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)))
                        .addGap(27, 27, 27)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(botonDevolver)
                        .addGap(50, 50, 50)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(67, 67, 67))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea devolver estos productos?");
        if (opc == JOptionPane.YES_OPTION) {
            try {
                String SQL = "INSERT INTO devolucionventas(\n"
                        + "	id_prd, id_vnt, devvt_date, canart)\n"
                        + "	VALUES (?, ?, ?, ?);";
                PreparedStatement devolucion = conn.prepareStatement(SQL);
                devolucion.setInt(1, id);
                devolucion.setInt(2, nV);

                Calendar date = Calendar.getInstance();
                SimpleDateFormat dateformatter = new SimpleDateFormat("yyyy-MM-dd");
                fecha = dateformatter.format(date.getTime());
                JLabel etq2 = new JLabel(fecha);

                devolucion.setDate(3, java.sql.Date.valueOf(etq2.getText()));
                devolucion.setInt(4, articulos);

                devolucion.executeUpdate();
                JOptionPane.showMessageDialog(this, "Productos devueltos con éxito");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error con la devolución.\n" + e);
            }
            try {
                String SQL2 = "UPDATE productos"
                        + "SET"
                        + "     prd_exist = prd_exist + ?"
                        + "WHERE "
                        + "     id_prd = " + id + "";
                PreparedStatement actualizar = conn.prepareStatement(SQL2);
                actualizar.setInt(1, articulos);
                JOptionPane.showMessageDialog(this, "Actualización de la cantidad exitosa.");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Ocurrió un error con la actualización de la existencia.\n" + e);
            }
            try {
                dev.consultaVentasGen(tablaContenido);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "Error en la consulta de las ventas\n" + ex);
            } catch (IOException ex) {
                Logger.getLogger(Devoluciones.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {

        }
    }//GEN-LAST:event_botonDevolverActionPerformed

    private void busquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyTyped
        char car = evt.getKeyChar();
        if ((car < '0' || car > '9') && (car < 'A' || car > 'Z') && (car < 'a' || car > 'z') && (car < '-' || car > '-')) {
            evt.consume();
        }
    }//GEN-LAST:event_busquedaKeyTyped

    private void busquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busquedaMouseClicked
        busqueda.setText("");
    }//GEN-LAST:event_busquedaMouseClicked

    private void busquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busquedaFocusGained
        if (busqueda.getText().equals("Folio de la venta...")) {
            busqueda.setText("");
        }
    }//GEN-LAST:event_busquedaFocusGained

    private void busquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_busquedaFocusLost
        if (busqueda.getText().equals("")) {
            busqueda.setText("Folio de la venta...");
        }
    }//GEN-LAST:event_busquedaFocusLost

    private void tablaContenidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaContenidoMousePressed
        tablaContenido.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                int fila = tablaContenido.rowAtPoint(e.getPoint());
                int columna = tablaContenido.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
                    id = (int) tablaContenido.getValueAt(fila, 1);
                    nV = (int) tablaContenido.getValueAt(fila, 0);
                    articulos = (int) tablaContenido.getValueAt(fila, 4);
                    botonDevolver.setEnabled(true);
                }
            }
        });
    }//GEN-LAST:event_tablaContenidoMousePressed

    private void busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_busquedaKeyReleased
        try {
            if (busqueda.getText().equals("")) { // Siempre que la búsqueda sea un vacio, se mostrarán todos los productos.
                dev.consultaVentasGen(tablaContenido);
            } else { // Búsqueda individual / conjunto.
                dev.consultaVentasInd(busqueda.getText(), tablaContenido);
            }
        } catch (SQLException ex) {

        }catch(IOException e){
        }
    }//GEN-LAST:event_busquedaKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonDevolver;
    private javax.swing.JTextField busqueda;
    private javax.swing.JLabel etqCalendar;
    private javax.swing.JLabel etqFolio;
    private javax.swing.JLabel fechaDevolucion;
    private javax.swing.JLabel folio;
    private javax.swing.JLabel hora;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lupa;
    private javax.swing.JTable tablaContenido;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel user;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            reloj.establecerHora();
            if (reloj.getMeridiem() == 1) {
                hora.setText(reloj.getHora() + ":" + reloj.getMinuto() + ":" + reloj.getSegundo() + " PM");
            } else {
                hora.setText(reloj.getHora() + ":" + reloj.getMinuto() + ":" + reloj.getSegundo() + " AM");
            }
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
}
