/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JTextField;

/**
 *
 * @author PC
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    ProductosBD abc = new ProductosBD();
    CategoriaBD def = new CategoriaBD();
    MarcasBD ghi = new MarcasBD();
    //Busqueda jkl = new Busqueda();

    private ResultSet resultado;
    private ResultSet resultado2;
    private Statement sql;

    boolean productoAux;
    boolean marcaAux;
    boolean categoriaAux;
    ArrayList<String> arreglo = new ArrayList<String>();
    ArrayList<String> arreglo2 = new ArrayList<String>();
    ArrayList<String> arreglo3 = new ArrayList<String>();

    DefaultListModel MODELO;
    int Enter = 0;

    public Productos(String nombre) throws SQLException, IOException {
        initComponents();
        //Codigo para llenar Listas
        ListaMarcas();
        ListaCategorias();
        
        //Codigo para desactivar casillas
        listaCategoriaProduc.setEnabled(false);
        listaMarcaProduc.setEnabled(false);
        descripcionCategoria.setEnabled(false);
        descripcionMarca.setEnabled(false);
        nombreProducto.setEnabled(false);
        nombreMarca.setEnabled(false);
        nombreCategoria.setEnabled(false);
        nombreUsuario.setText(nombre);
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        panelPresentaciones = new javax.swing.JPanel();
        panelMarca = new javax.swing.JPanel();
        botonNuevaMarca = new javax.swing.JButton();
        botonEditarMarca = new javax.swing.JButton();
        etiqnombreMarca = new javax.swing.JLabel();
        nombreMarca = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripcionMarca = new javax.swing.JTextArea();
        botonEditCategoria = new javax.swing.JButton();
        botonNuevaCategoria = new javax.swing.JButton();
        etqNombreCategoria = new javax.swing.JLabel();
        nombreCategoria = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        descripcionCategoria = new javax.swing.JTextArea();
        panelProductos = new javax.swing.JPanel();
        botonEditarProducto = new javax.swing.JButton();
        etqNombre = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        listaCategoriaProduc = new javax.swing.JComboBox<>();
        listaMarcaProduc = new javax.swing.JComboBox<>();
        botonNuevoProducto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 47, 87));
        setPreferredSize(new java.awt.Dimension(1222, 765));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        guardarButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });
        add(guardarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, -1, -1));

        eliminarButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 580, -1, -1));

        tituloLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 60)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("Productos");
        add(tituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(305, 13, -1, -1));

        botonNuevaMarca.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonNuevaMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        botonNuevaMarca.setText("Nueva Marca");
        botonNuevaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaMarcaActionPerformed(evt);
            }
        });

        botonEditarMarca.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonEditarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        botonEditarMarca.setText("Editar");

        etiqnombreMarca.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etiqnombreMarca.setText("Nombre:");

        nombreMarca.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        nombreMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreMarcaFocusLost(evt);
            }
        });
        nombreMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreMarcaKeyTyped(evt);
            }
        });

        descripcionMarca.setColumns(20);
        descripcionMarca.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        descripcionMarca.setRows(5);
        descripcionMarca.setText("Descripción");
        descripcionMarca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionMarcaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcionMarcaFocusLost(evt);
            }
        });
        descripcionMarca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcionMarcaKeyTyped(evt);
            }
        });
        jScrollPane3.setViewportView(descripcionMarca);

        javax.swing.GroupLayout panelMarcaLayout = new javax.swing.GroupLayout(panelMarca);
        panelMarca.setLayout(panelMarcaLayout);
        panelMarcaLayout.setHorizontalGroup(
            panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMarcaLayout.createSequentialGroup()
                        .addComponent(botonNuevaMarca)
                        .addGap(66, 66, 66)
                        .addComponent(botonEditarMarca))
                    .addGroup(panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMarcaLayout.createSequentialGroup()
                            .addComponent(etiqnombreMarca)
                            .addGap(18, 18, 18)
                            .addComponent(nombreMarca))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMarcaLayout.setVerticalGroup(
            panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaMarca)
                    .addComponent(botonEditarMarca))
                .addGap(30, 30, 30)
                .addGroup(panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqnombreMarca)
                    .addComponent(nombreMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        botonEditCategoria.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonEditCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        botonEditCategoria.setText("Editar");
        botonEditCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditCategoriaActionPerformed(evt);
            }
        });

        botonNuevaCategoria.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonNuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        botonNuevaCategoria.setText("Nueva Categoria");
        botonNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevaCategoriaActionPerformed(evt);
            }
        });

        etqNombreCategoria.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqNombreCategoria.setText("Nombre: ");

        nombreCategoria.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        nombreCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreCategoriaFocusLost(evt);
            }
        });
        nombreCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreCategoriaKeyTyped(evt);
            }
        });

        descripcionCategoria.setColumns(20);
        descripcionCategoria.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        descripcionCategoria.setRows(5);
        descripcionCategoria.setText("Descripción");
        descripcionCategoria.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                descripcionCategoriaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                descripcionCategoriaFocusLost(evt);
            }
        });
        descripcionCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                descripcionCategoriaKeyTyped(evt);
            }
        });
        jScrollPane4.setViewportView(descripcionCategoria);

        javax.swing.GroupLayout panelPresentacionesLayout = new javax.swing.GroupLayout(panelPresentaciones);
        panelPresentaciones.setLayout(panelPresentacionesLayout);
        panelPresentacionesLayout.setHorizontalGroup(
            panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEditCategoria)
                .addGap(37, 37, 37))
            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPresentacionesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPresentacionesLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                                .addComponent(etqNombreCategoria)
                                .addGap(18, 18, 18)
                                .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(botonNuevaCategoria))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPresentacionesLayout.setVerticalGroup(
            panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditCategoria)
                    .addComponent(botonNuevaCategoria))
                .addGap(30, 30, 30)
                .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqNombreCategoria)
                    .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelPresentaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(715, 96, -1, -1));

        panelProductos.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        botonEditarProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        botonEditarProducto.setText("Editar");
        botonEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarProductoActionPerformed(evt);
            }
        });

        etqNombre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqNombre.setText("Nombre:");

        nombreProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        nombreProducto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nombreProductoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                nombreProductoFocusLost(evt);
            }
        });
        nombreProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreProductoKeyTyped(evt);
            }
        });

        listaCategoriaProduc.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        listaCategoriaProduc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        listaCategoriaProduc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                listaCategoriaProducItemStateChanged(evt);
            }
        });

        listaMarcaProduc.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        listaMarcaProduc.setToolTipText("");

        botonNuevoProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        botonNuevoProducto.setText("Nuevo Producto");
        botonNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(etqNombre)
                        .addGap(18, 18, 18)
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listaCategoriaProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaMarcaProduc, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(botonNuevoProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addComponent(botonEditarProducto)))
                .addContainerGap())
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqNombre)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(listaCategoriaProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(listaMarcaProduc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        listaMarcaProduc.getAccessibleContext().setAccessibleName("Marca");
        listaMarcaProduc.getAccessibleContext().setAccessibleDescription("Marca");

        add(panelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 410, 330));

        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        jButton1.setText("Busqueda");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario2.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        nombreUsuario.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 22)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setText("jLabel2");
        add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ListaMarcas() throws SQLException, IOException {
        listaMarcaProduc.removeAllItems();
        listaMarcaProduc.addItem("Marca...");

        arreglo = abc.llenarlistaMarcas();
        listaMarcaProduc.setMaximumRowCount(arreglo.size() + 1);

        for (int b = 0; b < arreglo.size(); b++) {
            listaMarcaProduc.addItem(arreglo.get(b));
        }

    }

    private void ListaCategorias() throws SQLException, IOException {
        listaCategoriaProduc.removeAllItems();
        listaCategoriaProduc.addItem("Categoría...");

        arreglo2 = abc.llenarlistaCategorias();
        listaCategoriaProduc.setMaximumRowCount(arreglo2.size() + 1);

        for (int b = 0; b < arreglo2.size(); b++) {
            listaCategoriaProduc.addItem(arreglo2.get(b));
        }

    }
    public void first(ArrayList<String> arr) {
        

            for (int i = 0; i < arr.size(); i++) {
                arreglo3.add(arr.get(i));
                System.out.println("first--------"+arreglo3);
                
            }
            
            JOptionPane.showMessageDialog(this, "fin de first");
        
    }
    



    private void botonEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEditarProductoActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed

        if (categoriaAux == true) {
            int opc = JOptionPane.showConfirmDialog(this, "¿Desea guardar todos los cambios?");
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    def.setNombreCtgo(nombreCategoria.getText());
                    def.setDescripcionCtgo(descripcionCategoria.getText());
                    def.agregarCategoria();
                    nombreCategoria.setText("");
                    nombreCategoria.setEnabled(false);
                    descripcionCategoria.setText("Descripción");
                    descripcionCategoria.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Cambios guardados con éxito.");
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (productoAux == true) {
            int opc = JOptionPane.showConfirmDialog(this, "¿Desea guardar todos los cambios?");
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    abc.setNombreProduc(nombreProducto.getText());
                    abc.setCategoriaProduc(listaCategoriaProduc.getSelectedItem().toString());
                    abc.setMarcaProduc(listaMarcaProduc.getSelectedItem().toString());
                    abc.agregarProducto();
                    nombreProducto.setText("");
                    nombreProducto.setEnabled(false);
                    listaCategoriaProduc.setEnabled(false);
                    listaMarcaProduc.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Cambios guardados con éxito.");
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if (marcaAux == true) {
            int opc = JOptionPane.showConfirmDialog(this, "¿Desea guardar todos los cambios?");
            if (opc == JOptionPane.YES_OPTION) {
                try {
                    ghi.setNombreMrc(nombreMarca.getText());
                    ghi.setDescripcionMrc(descripcionMarca.getText());
                    ghi.agregarMarca();
                    nombreMarca.setText("");
                    nombreMarca.setEnabled(false);
                    descripcionMarca.setText("Descripción");
                    descripcionMarca.setEnabled(false);
                    JOptionPane.showMessageDialog(this, "Cambios guardados con éxito.");
                } catch (SQLException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nooooooooooooooooooo T.T");
        }

    }//GEN-LAST:event_guardarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea cancelar los cambios?");
        if (opc == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Cancelación exitosa.");
        } else {

        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void botonNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoProductoActionPerformed
        // TODO add your handling code here:
        nombreProducto.setEnabled(true);
        listaCategoriaProduc.setEnabled(true);
        listaMarcaProduc.setEnabled(true);
        try {
            arreglo.clear();
            ListaMarcas();
            arreglo2.clear();
            ListaCategorias();
        } catch (SQLException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Productos.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (evt.getSource().equals(botonNuevoProducto)) {
            categoriaAux = false;
            productoAux = true;
            marcaAux = false;
        }

        nombreCategoria.setEnabled(false);
        descripcionCategoria.setEnabled(false);
        nombreMarca.setEnabled(false);
        descripcionMarca.setEnabled(false);
    }//GEN-LAST:event_botonNuevoProductoActionPerformed

    private void nombreProductoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreProductoFocusGained
        // TODO add your handling code here:
        if (nombreProducto.getText().equals("Buscar.....")) {
            nombreProducto.setText("");
        }
    }//GEN-LAST:event_nombreProductoFocusGained

    private void nombreProductoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreProductoFocusLost
        // TODO add your handling code here:
        if (nombreProducto.getText().equals("")) {
            nombreProducto.setText("Buscar.....");
        }
    }//GEN-LAST:event_nombreProductoFocusLost

    private void nombreCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreCategoriaFocusGained
        // TODO add your handling code here:
        if (nombreCategoria.getText().equals("Buscar.....")) {
            nombreCategoria.setText("");
        }
    }//GEN-LAST:event_nombreCategoriaFocusGained

    private void nombreCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreCategoriaFocusLost
        // TODO add your handling code here:
        if (nombreCategoria.getText().equals("")) {
            nombreCategoria.setText("Buscar.....");
        }
    }//GEN-LAST:event_nombreCategoriaFocusLost

    private void nombreMarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreMarcaFocusGained
        // TODO add your handling code here:
        if (nombreMarca.getText().equals("Buscar.....")) {
            nombreMarca.setText("");
        }
    }//GEN-LAST:event_nombreMarcaFocusGained

    private void nombreMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nombreMarcaFocusLost
        // TODO add your handling code here:
        if (nombreMarca.getText().equals("")) {
            nombreMarca.setText("Buscar.....");
        }
    }//GEN-LAST:event_nombreMarcaFocusLost

    private void botonNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaCategoriaActionPerformed
        // TODO add your handling code here:
        descripcionCategoria.setEnabled(true);
        nombreCategoria.setEnabled(true);
        if (evt.getSource().equals(botonNuevaCategoria)) {
            categoriaAux = true;
            productoAux = false;
            marcaAux = false;
        }

        nombreProducto.setEnabled(false);
        listaCategoriaProduc.setEnabled(false);
        listaMarcaProduc.setEnabled(false);
        nombreMarca.setEnabled(false);
        descripcionMarca.setEnabled(false);
    }//GEN-LAST:event_botonNuevaCategoriaActionPerformed

    private void botonNuevaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevaMarcaActionPerformed
        // TODO add your handling code here:
        descripcionMarca.setEnabled(true);
        nombreMarca.setEnabled(true);

        if (evt.getSource().equals(botonNuevaMarca)) {
            categoriaAux = false;
            productoAux = false;
            marcaAux = true;
        }

        nombreProducto.setEnabled(false);
        listaCategoriaProduc.setEnabled(false);
        listaMarcaProduc.setEnabled(false);
        nombreCategoria.setEnabled(false);
        descripcionCategoria.setEnabled(false);
    }//GEN-LAST:event_botonNuevaMarcaActionPerformed

    private void descripcionMarcaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionMarcaFocusGained
        // TODO add your handling code here:
        if (descripcionMarca.getText().equals("Descripción")) {
            descripcionMarca.setText("");
        }
    }//GEN-LAST:event_descripcionMarcaFocusGained

    private void descripcionMarcaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionMarcaFocusLost
        // TODO add your handling code here:
        if (descripcionMarca.getText().equals("")) {
            descripcionMarca.setText("Descripción");
        }
    }//GEN-LAST:event_descripcionMarcaFocusLost

    private void descripcionCategoriaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionCategoriaFocusGained
        // TODO add your handling code here:
        if (descripcionCategoria.getText().equals("Descripción")) {
            descripcionCategoria.setText("");
        }
    }//GEN-LAST:event_descripcionCategoriaFocusGained

    private void descripcionCategoriaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_descripcionCategoriaFocusLost
        // TODO add your handling code here:
        if (descripcionCategoria.getText().equals("")) {
            descripcionCategoria.setText("Descripción");
        }
    }//GEN-LAST:event_descripcionCategoriaFocusLost

    private void listaCategoriaProducItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_listaCategoriaProducItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_listaCategoriaProducItemStateChanged

    private void nombreCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCategoriaKeyTyped
        // TODO add your handling code here:

        if (nombreCategoria.getText().length() == 15) {
            evt.consume();
        }

    }//GEN-LAST:event_nombreCategoriaKeyTyped

    private void descripcionCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionCategoriaKeyTyped
        // TODO add your handling code here:
        if (descripcionCategoria.getText().length() == 23) {
            evt.consume();
        }
    }//GEN-LAST:event_descripcionCategoriaKeyTyped

    private void nombreMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreMarcaKeyTyped
        // TODO add your handling code here
        if (nombreMarca.getText().length() == 15) {
            evt.consume();
        }
    }//GEN-LAST:event_nombreMarcaKeyTyped

    private void descripcionMarcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcionMarcaKeyTyped
        // TODO add your handling code here:
        if (descripcionMarca.getText().length() == 23) {
            evt.consume();
        }
    }//GEN-LAST:event_descripcionMarcaKeyTyped

    private void nombreProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreProductoKeyTyped
        // TODO add your handling code here:
        if (nombreProducto.getText().length() == 30) {
            evt.consume();
        }
    }//GEN-LAST:event_nombreProductoKeyTyped

    private void botonEditCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEditCategoriaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Busqueda obj = new Busqueda(nombreUsuario.getText());
        obj.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
            nombreProducto.setEnabled(true);
           
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditCategoria;
    private javax.swing.JButton botonEditarMarca;
    private javax.swing.JButton botonEditarProducto;
    private javax.swing.JButton botonNuevaCategoria;
    private javax.swing.JButton botonNuevaMarca;
    private javax.swing.JButton botonNuevoProducto;
    private javax.swing.JTextArea descripcionCategoria;
    private javax.swing.JTextArea descripcionMarca;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel etiqnombreMarca;
    private javax.swing.JLabel etqNombre;
    private javax.swing.JLabel etqNombreCategoria;
    private javax.swing.JButton guardarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JComboBox<String> listaCategoriaProduc;
    private javax.swing.JComboBox<String> listaMarcaProduc;
    private javax.swing.JTextField nombreCategoria;
    private javax.swing.JTextField nombreMarca;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JPanel panelMarca;
    private javax.swing.JPanel panelPresentaciones;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
