/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import javax.swing.JOptionPane;
import static puntodeventa.Principal.contenedor;

/**
 *
 * @author PC
 */
public class Productos extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public Productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guardarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        tituloLabel = new javax.swing.JLabel();
        panelPresentaciones = new javax.swing.JPanel();
        botonNuevaPresentacion = new javax.swing.JButton();
        editarPrese = new javax.swing.JButton();
        buscarPresen = new javax.swing.JTextField();
        etqPrecio = new javax.swing.JLabel();
        etqFuncion = new javax.swing.JLabel();
        campoPrecioPrese = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        panelMarca = new javax.swing.JPanel();
        botonNuevaMarca = new javax.swing.JButton();
        botonEditarMarca = new javax.swing.JButton();
        nombreMarca = new javax.swing.JLabel();
        marca = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        descripcionMarca = new javax.swing.JTextArea();
        panelProductos = new javax.swing.JPanel();
        botonEditarProducto = new javax.swing.JButton();
        etqNombre = new javax.swing.JLabel();
        nombreProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionProducto = new javax.swing.JTextArea();
        etqExistencia = new javax.swing.JLabel();
        existenciaProducto = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        panelCategorias = new javax.swing.JPanel();
        botonNuevaCategoria = new javax.swing.JButton();
        botonEditCategoria = new javax.swing.JButton();
        etqNombreCategoria = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        descripcionCategoria = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(1, 47, 87));

        guardarButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        guardarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        eliminarButton.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        eliminarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        tituloLabel.setBackground(new java.awt.Color(255, 255, 255));
        tituloLabel.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 60)); // NOI18N
        tituloLabel.setForeground(new java.awt.Color(255, 255, 255));
        tituloLabel.setText("Productos");

        botonNuevaPresentacion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonNuevaPresentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        botonNuevaPresentacion.setText("Nueva Presentación");

        editarPrese.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        editarPrese.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        editarPrese.setText("Editar");

        buscarPresen.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        buscarPresen.setText("Buscar...");

        etqPrecio.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqPrecio.setText("Precio:");

        etqFuncion.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqFuncion.setText("Función:");

        campoPrecioPrese.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        botonNuevaMarca.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonNuevaMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        botonNuevaMarca.setText("Nueva Marca");

        botonEditarMarca.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonEditarMarca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        botonEditarMarca.setText("Editar");

        nombreMarca.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        nombreMarca.setText("Nombre:");

        marca.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        marca.setText("Buscar...");

        descripcionMarca.setColumns(20);
        descripcionMarca.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        descripcionMarca.setRows(5);
        descripcionMarca.setText("Descripción");
        jScrollPane3.setViewportView(descripcionMarca);

        javax.swing.GroupLayout panelMarcaLayout = new javax.swing.GroupLayout(panelMarca);
        panelMarca.setLayout(panelMarcaLayout);
        panelMarcaLayout.setHorizontalGroup(
            panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMarcaLayout.createSequentialGroup()
                        .addComponent(botonNuevaMarca)
                        .addGap(66, 66, 66)
                        .addComponent(botonEditarMarca))
                    .addGroup(panelMarcaLayout.createSequentialGroup()
                        .addComponent(nombreMarca)
                        .addGap(18, 18, 18)
                        .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        panelMarcaLayout.setVerticalGroup(
            panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarcaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaMarca)
                    .addComponent(botonEditarMarca))
                .addGap(30, 30, 30)
                .addGroup(panelMarcaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreMarca)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPresentacionesLayout = new javax.swing.GroupLayout(panelPresentaciones);
        panelPresentaciones.setLayout(panelPresentacionesLayout);
        panelPresentacionesLayout.setHorizontalGroup(
            panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelPresentacionesLayout.createSequentialGroup()
                        .addComponent(etqFuncion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8))
                    .addGroup(panelPresentacionesLayout.createSequentialGroup()
                        .addComponent(etqPrecio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoPrecioPrese))
                    .addComponent(buscarPresen, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevaPresentacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarPrese)
                .addGap(90, 90, 90))
            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                .addComponent(panelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelPresentacionesLayout.setVerticalGroup(
            panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPresentacionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaPresentacion)
                    .addComponent(editarPrese))
                .addGap(29, 29, 29)
                .addComponent(buscarPresen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqPrecio)
                    .addComponent(campoPrecioPrese, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelPresentacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqFuncion)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );

        panelProductos.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N

        botonEditarProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonEditarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        botonEditarProducto.setText("Editar");
        botonEditarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEditarProductoActionPerformed(evt);
            }
        });

        etqNombre.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqNombre.setText("Nombre:");

        nombreProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        nombreProducto.setText("Buscar...");

        descripcionProducto.setColumns(20);
        descripcionProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        descripcionProducto.setRows(5);
        descripcionProducto.setText("Descripción");
        jScrollPane1.setViewportView(descripcionProducto);

        etqExistencia.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqExistencia.setText("Existencia:");

        existenciaProducto.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        existenciaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existenciaProductoActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Categoría" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Marca" }));

        jComboBox3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Presentación" }));

        botonNuevaCategoria.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonNuevaCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        botonNuevaCategoria.setText("Nueva Categoria");

        botonEditCategoria.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        botonEditCategoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        botonEditCategoria.setText("Editar");

        etqNombreCategoria.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        etqNombreCategoria.setText("Nombre: ");

        jTextField1.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        jTextField1.setText("Buscar...");

        descripcionCategoria.setColumns(20);
        descripcionCategoria.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 18)); // NOI18N
        descripcionCategoria.setRows(5);
        descripcionCategoria.setText("Descripción");
        jScrollPane4.setViewportView(descripcionCategoria);

        javax.swing.GroupLayout panelCategoriasLayout = new javax.swing.GroupLayout(panelCategorias);
        panelCategorias.setLayout(panelCategoriasLayout);
        panelCategoriasLayout.setHorizontalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonNuevaCategoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonEditCategoria)
                .addGap(84, 84, 84))
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCategoriasLayout.createSequentialGroup()
                        .addComponent(etqNombreCategoria)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCategoriasLayout.setVerticalGroup(
            panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonNuevaCategoria)
                    .addComponent(botonEditCategoria))
                .addGap(36, 36, 36)
                .addGroup(panelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etqNombreCategoria)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelProductosLayout = new javax.swing.GroupLayout(panelProductos);
        panelProductos.setLayout(panelProductosLayout);
        panelProductosLayout.setHorizontalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelProductosLayout.createSequentialGroup()
                                .addComponent(etqNombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreProducto))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(botonEditarProducto))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelProductosLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(etqExistencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(existenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))))
                    .addComponent(panelCategorias, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panelProductosLayout.setVerticalGroup(
            panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonEditarProducto)
                    .addComponent(etqNombre)
                    .addComponent(nombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelProductosLayout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etqExistencia)
                    .addComponent(existenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(guardarButton)
                        .addGap(29, 29, 29)
                        .addComponent(eliminarButton)
                        .addGap(65, 65, 65))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panelPresentaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 55, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(305, 305, 305)
                .addComponent(tituloLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(tituloLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarButton)
                    .addComponent(eliminarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelPresentaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void existenciaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existenciaProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existenciaProductoActionPerformed

    private void botonEditarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEditarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonEditarProductoActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea guardar todos los cambios?");
        if (opc == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,"Cambios guardados con éxito.");
        }else{
            
        }
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea cancelar los cambios?");
        if (opc == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this,"Cancelación exitosa.");
        }else{
            
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonEditCategoria;
    private javax.swing.JButton botonEditarMarca;
    private javax.swing.JButton botonEditarProducto;
    private javax.swing.JButton botonNuevaCategoria;
    private javax.swing.JButton botonNuevaMarca;
    private javax.swing.JButton botonNuevaPresentacion;
    private javax.swing.JTextField buscarPresen;
    private javax.swing.JTextField campoPrecioPrese;
    private javax.swing.JTextArea descripcionCategoria;
    private javax.swing.JTextArea descripcionMarca;
    private javax.swing.JTextArea descripcionProducto;
    private javax.swing.JButton editarPrese;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel etqExistencia;
    private javax.swing.JLabel etqFuncion;
    private javax.swing.JLabel etqNombre;
    private javax.swing.JLabel etqNombreCategoria;
    private javax.swing.JLabel etqPrecio;
    private javax.swing.JTextField existenciaProducto;
    private javax.swing.JButton guardarButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField marca;
    private javax.swing.JLabel nombreMarca;
    private javax.swing.JTextField nombreProducto;
    private javax.swing.JPanel panelCategorias;
    private javax.swing.JPanel panelMarca;
    private javax.swing.JPanel panelPresentaciones;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JLabel tituloLabel;
    // End of variables declaration//GEN-END:variables
}
