/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import static puntodeventa.Principal.contenedor;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Carmen, Se quitó email temporalmente, hasta modificación de la BD
 */
public class Proveedores extends javax.swing.JPanel {

    /**
     * Creates new form Proveedores
     */
    Calendario cal = new Calendario();
    ProveedoresBD pb = new ProveedoresBD();

    public Proveedores() {
        initComponents();
        pb.consultarProveedor(jTable1);
        TelefonoProveedor.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                if (!Character.isDigit(e.getKeyChar()) || TelefonoProveedor.getText().length() > 10) {
                    e.consume();
                    getToolkit().beep();
                }
            }
        });

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buscar = new javax.swing.JTextField();
        lupa = new javax.swing.JLabel();
        addProveedor = new javax.swing.JButton();
        titulo = new javax.swing.JLabel();
        editarProveedor = new javax.swing.JButton();
        etqnombre = new javax.swing.JLabel();
        nombreProveedor = new javax.swing.JTextField();
        apellidoP = new javax.swing.JLabel();
        ApellidoPaternoProveedor = new javax.swing.JTextField();
        apellidoM = new javax.swing.JLabel();
        ApellidoMaternoProveedor = new javax.swing.JTextField();
        tele = new javax.swing.JLabel();
        mf = new javax.swing.JComboBox<>();
        sexo = new javax.swing.JLabel();
        TelefonoProveedor = new javax.swing.JTextField();
        fechaNac = new javax.swing.JLabel();
        fechaNacimientoProveedor = new javax.swing.JTextField();
        GuardarProveedor = new javax.swing.JButton();
        eliminarProveedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        calendarioProveedor = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 47, 83));
        setPreferredSize(new java.awt.Dimension(1365, 765));

        buscar.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        buscar.setText("ßuscar....");
        buscar.setToolTipText("");
        buscar.setCaretColor(new java.awt.Color(0, 0, 153));
        buscar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        buscar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                buscarFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                buscarFocusLost(evt);
            }
        });
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });

        addProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        addProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        addProveedor.setText(" Agregar Proveedor");
        addProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProveedorActionPerformed(evt);
            }
        });

        titulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 60)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Proveedores");

        editarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        editarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        editarProveedor.setText("Editar Proveedor");

        etqnombre.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        etqnombre.setForeground(new java.awt.Color(255, 255, 255));
        etqnombre.setText("Nombre: ");

        nombreProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N

        apellidoP.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        apellidoP.setForeground(new java.awt.Color(255, 255, 255));
        apellidoP.setText("Apellido P: ");

        ApellidoPaternoProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N

        apellidoM.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        apellidoM.setForeground(new java.awt.Color(255, 255, 255));
        apellidoM.setText("Apellido M: ");

        ApellidoMaternoProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N

        tele.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        tele.setForeground(new java.awt.Color(255, 255, 255));
        tele.setText("Telefono:");

        mf.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        mf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        mf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mfActionPerformed(evt);
            }
        });

        sexo.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        sexo.setForeground(new java.awt.Color(255, 255, 255));
        sexo.setText("Sexo:");

        TelefonoProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N

        fechaNac.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N
        fechaNac.setForeground(new java.awt.Color(255, 255, 255));
        fechaNac.setText("F. Nacimiento:");

        fechaNacimientoProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 17)); // NOI18N

        GuardarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        GuardarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        GuardarProveedor.setText("Guardar");
        GuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarProveedorActionPerformed(evt);
            }
        });

        eliminarProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        eliminarProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        eliminarProveedor.setText("Eliminar");
        eliminarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProveedorActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido Paterno", "Apellido Materno", "Sexo", "Telefono", "Fecha Nacimiento"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        calendarioProveedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calendario.png"))); // NOI18N
        calendarioProveedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioProveedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(lupa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 730, Short.MAX_VALUE)
                        .addComponent(titulo)
                        .addGap(240, 240, 240))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etqnombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apellidoM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tele, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sexo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fechaNac))
                        .addGap(33, 33, 33)
                        .addComponent(fechaNacimientoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calendarioProveedor))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(addProveedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(editarProveedor)))
                .addGap(172, 172, 172)
                .addComponent(GuardarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(eliminarProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(apellidoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoPaternoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ApellidoMaternoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ApellidoMaternoProveedor, ApellidoPaternoProveedor, TelefonoProveedor, fechaNacimientoProveedor, nombreProveedor});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GuardarProveedor)
                    .addComponent(eliminarProveedor))
                .addGap(79, 79, 79))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(calendarioProveedor)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lupa))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(etqnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApellidoPaternoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(apellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ApellidoMaternoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mf, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tele, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fechaNacimientoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addProveedor)
                    .addComponent(editarProveedor))
                .addGap(0, 118, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ApellidoMaternoProveedor, ApellidoPaternoProveedor, TelefonoProveedor, fechaNacimientoProveedor, nombreProveedor});

    }// </editor-fold>//GEN-END:initComponents

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed

    }//GEN-LAST:event_buscarActionPerformed

    private void buscarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarFocusGained
        if (buscar.getText().equals("ßuscar....")) {
            buscar.setText("");
        }

    }//GEN-LAST:event_buscarFocusGained

    private void buscarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_buscarFocusLost
        if (buscar.getText().equals("")) {
            buscar.setText("ßuscar....");
        }
    }//GEN-LAST:event_buscarFocusLost

    private void addProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addProveedorActionPerformed

    private void mfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mfActionPerformed

    private void GuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarProveedorActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea guardar todos los cambios?");
        if (opc == JOptionPane.YES_OPTION) {
            pb.setNombre(nombreProveedor.getText());
            pb.setApellido_p(ApellidoPaternoProveedor.getText());
            pb.setApellido_m(ApellidoMaternoProveedor.getText());
            pb.setTelefono(TelefonoProveedor.getText());
            pb.setFecha(fechaNacimientoProveedor.getText());
            pb.setSexo(mf.getSelectedItem().toString().charAt(0));
            pb.agregarProveedor();
            nombreProveedor.setText("");
            ApellidoPaternoProveedor.setText("");
            ApellidoMaternoProveedor.setText("");
            TelefonoProveedor.setText("");
            fechaNacimientoProveedor.setText("");
            JOptionPane.showMessageDialog(this, "Cambios guardados con éxito.");
            pb.consultarProveedor(jTable1);
        } else {

        }
    }//GEN-LAST:event_GuardarProveedorActionPerformed

    private void eliminarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProveedorActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea eliminar al proveedor?");
        if (opc == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Proveedor borrado con éxito.");
        } else {

        }
    }//GEN-LAST:event_eliminarProveedorActionPerformed

    private void calendarioProveedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioProveedorMouseClicked
        // TODO add your handling code here:
        cal.setVisible(true);

    }//GEN-LAST:event_calendarioProveedorMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoMaternoProveedor;
    private javax.swing.JTextField ApellidoPaternoProveedor;
    private javax.swing.JButton GuardarProveedor;
    private javax.swing.JTextField TelefonoProveedor;
    private javax.swing.JButton addProveedor;
    private javax.swing.JLabel apellidoM;
    private javax.swing.JLabel apellidoP;
    private javax.swing.JTextField buscar;
    private javax.swing.JLabel calendarioProveedor;
    private javax.swing.JButton editarProveedor;
    private javax.swing.JButton eliminarProveedor;
    private javax.swing.JLabel etqnombre;
    private javax.swing.JLabel fechaNac;
    private javax.swing.JTextField fechaNacimientoProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lupa;
    private javax.swing.JComboBox<String> mf;
    private javax.swing.JTextField nombreProveedor;
    private javax.swing.JLabel sexo;
    private javax.swing.JLabel tele;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
