/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puntodeventa;

import javax.swing.JOptionPane;
import static puntodeventa.Principal.contenedor;

/**
 *
 * @author Carmen
 */
public class Ventas extends javax.swing.JPanel {

    /**
     * Creates new form Ventas
     */
    public Ventas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        userVenta = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ApellidoPaternoProveedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nombreProveedor = new javax.swing.JTextField();
        addVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVenta = new javax.swing.JTable();
        realizarVenta = new javax.swing.JButton();
        cancelarVENTA = new javax.swing.JButton();
        familyVENTA = new javax.swing.JButton();
        etiquetaTotal = new javax.swing.JLabel();
        totalEtiqueta = new javax.swing.JLabel();
        totalEtiqueta1 = new javax.swing.JLabel();
        nombreUsuario = new javax.swing.JLabel();
        botonDevoluciones = new javax.swing.JButton();
        calendario = new javax.swing.JLabel();
        fecha = new javax.swing.JLabel();

        setBackground(new java.awt.Color(1, 47, 83));
        setPreferredSize(new java.awt.Dimension(1365, 765));

        titulo.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 75)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("Ventas");

        userVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario2.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 23)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. Venta:");

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Cantidad: ");

        ApellidoPaternoProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        ApellidoPaternoProveedor.setText("1");

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Producto:");

        nombreProveedor.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        nombreProveedor.setText("Nombre producto");

        addVenta.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        addVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/añadir.png"))); // NOI18N
        addVenta.setText(" Agregar");
        addVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVentaActionPerformed(evt);
            }
        });

        tablaVenta.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        tablaVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Nombre", "Descripción", "Subtotal", "Total"
            }
        ));
        jScrollPane1.setViewportView(tablaVenta);

        realizarVenta.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        realizarVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/finalizar.png"))); // NOI18N
        realizarVenta.setText("Realizar »");
        realizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVentaActionPerformed(evt);
            }
        });

        cancelarVENTA.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        cancelarVENTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/cancelar.png"))); // NOI18N
        cancelarVENTA.setText("Cancelar «");
        cancelarVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarVENTAActionPerformed(evt);
            }
        });

        familyVENTA.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 19)); // NOI18N
        familyVENTA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/familia.png"))); // NOI18N
        familyVENTA.setText("Familia");
        familyVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                familyVENTAActionPerformed(evt);
            }
        });

        etiquetaTotal.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        etiquetaTotal.setForeground(new java.awt.Color(255, 255, 255));
        etiquetaTotal.setText("Total:");

        totalEtiqueta.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 36)); // NOI18N
        totalEtiqueta.setForeground(new java.awt.Color(255, 255, 255));
        totalEtiqueta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalEtiqueta.setText("000.00");

        totalEtiqueta1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 23)); // NOI18N
        totalEtiqueta1.setForeground(new java.awt.Color(255, 255, 255));
        totalEtiqueta1.setText("000001");

        nombreUsuario.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        nombreUsuario.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuario.setText("Nombre_Usuario");

        botonDevoluciones.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 18)); // NOI18N
        botonDevoluciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/devoluciones.png"))); // NOI18N
        botonDevoluciones.setText("Devoluciones");
        botonDevoluciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolucionesActionPerformed(evt);
            }
        });

        calendario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/calendario.png"))); // NOI18N

        fecha.setFont(new java.awt.Font("Microsoft JhengHei UI", 1, 24)); // NOI18N
        fecha.setForeground(new java.awt.Color(255, 255, 255));
        fecha.setText("dd-mm-aaaa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(realizarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(addVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancelarVENTA)
                            .addComponent(familyVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(ApellidoPaternoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(calendario)
                                .addGap(18, 18, 18)
                                .addComponent(fecha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreUsuario)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(etiquetaTotal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalEtiqueta, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(136, 136, 136))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalEtiqueta1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(267, 267, 267))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(botonDevoluciones)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(titulo)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(userVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonDevoluciones)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(nombreUsuario))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(totalEtiqueta1)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaTotal)
                            .addComponent(totalEtiqueta)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(calendario)
                            .addComponent(fecha))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ApellidoPaternoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(familyVENTA, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(realizarVenta)
                            .addComponent(cancelarVENTA))))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ApellidoPaternoProveedor, nombreProveedor});

    }// </editor-fold>//GEN-END:initComponents

    private void addVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addVentaActionPerformed

    private void realizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVentaActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea realizar la venta?");
        if (opc == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Venta registrada.");
        } else {

        }
    }//GEN-LAST:event_realizarVentaActionPerformed

    private void cancelarVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarVENTAActionPerformed
        int opc = JOptionPane.showConfirmDialog(this, "¿Desea cancelar la venta");
        if (opc == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Cancelación exitosa.");
        } else {

        }
    }//GEN-LAST:event_cancelarVENTAActionPerformed

    private void familyVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_familyVENTAActionPerformed

        JOptionPane.showMessageDialog(this, "Registro de familia completado.");

    }//GEN-LAST:event_familyVENTAActionPerformed

    private void botonDevolucionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolucionesActionPerformed
        Devoluciones c = new Devoluciones();
        contenedor.removeAll();
        contenedor.add(c);
        contenedor.revalidate();
        contenedor.repaint();
    }//GEN-LAST:event_botonDevolucionesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ApellidoPaternoProveedor;
    private javax.swing.JButton addVenta;
    private javax.swing.JButton botonDevoluciones;
    private javax.swing.JLabel calendario;
    private javax.swing.JButton cancelarVENTA;
    private javax.swing.JLabel etiquetaTotal;
    private javax.swing.JButton familyVENTA;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreProveedor;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JButton realizarVenta;
    private javax.swing.JTable tablaVenta;
    private javax.swing.JLabel titulo;
    private javax.swing.JLabel totalEtiqueta;
    private javax.swing.JLabel totalEtiqueta1;
    private javax.swing.JLabel userVenta;
    // End of variables declaration//GEN-END:variables

}
